-- Data-only migration: fills per-portion nutrition for built-in categories on existing installs
-- (only where the user has not set any values) and creates the initial daily goals.
-- New installs get these values from src/db/defaultCategories.ts when seeding.
UPDATE `categories` SET `portion_label` = '1 bowl', `kcal` = 150, `fiber_g` = 4, `sugar_g` = 5 WHERE `seed_key` = 'salad' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 cup', `kcal` = 60, `fiber_g` = 4, `sugar_g` = 4 WHERE `seed_key` = 'vegetables' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 medium fruit', `kcal` = 95, `fiber_g` = 4, `sugar_g` = 19 WHERE `seed_key` = 'fruit' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '150 g fillet', `kcal` = 280, `fiber_g` = 0, `sugar_g` = 0 WHERE `seed_key` = 'fish' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '150 g', `kcal` = 250, `fiber_g` = 0, `sugar_g` = 0 WHERE `seed_key` = 'grilled_chicken' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '2 eggs', `kcal` = 155, `fiber_g` = 0, `sugar_g` = 1 WHERE `seed_key` = 'eggs' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 bowl', `kcal` = 250, `fiber_g` = 5, `sugar_g` = 8 WHERE `seed_key` = 'oatmeal' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 cup', `kcal` = 150, `fiber_g` = 0, `sugar_g` = 10 WHERE `seed_key` = 'yogurt' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '30 g handful', `kcal` = 180, `fiber_g` = 3, `sugar_g` = 1 WHERE `seed_key` = 'nuts' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 cup cooked', `kcal` = 230, `fiber_g` = 15, `sugar_g` = 2 WHERE `seed_key` = 'legumes' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 plate', `kcal` = 450, `fiber_g` = 4, `sugar_g` = 8 WHERE `seed_key` = 'pasta' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 cup cooked', `kcal` = 205, `fiber_g` = 1, `sugar_g` = 0 WHERE `seed_key` = 'rice' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '2 slices', `kcal` = 160, `fiber_g` = 2, `sugar_g` = 3 WHERE `seed_key` = 'bread' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 sandwich', `kcal` = 350, `fiber_g` = 3, `sugar_g` = 5 WHERE `seed_key` = 'sandwich' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '30 g', `kcal` = 110, `fiber_g` = 0, `sugar_g` = 0 WHERE `seed_key` = 'cheese' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '150 g', `kcal` = 375, `fiber_g` = 0, `sugar_g` = 0 WHERE `seed_key` = 'red_meat' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 medium potato', `kcal` = 160, `fiber_g` = 4, `sugar_g` = 2 WHERE `seed_key` = 'potatoes' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 cup', `kcal` = 50, `fiber_g` = 0, `sugar_g` = 10 WHERE `seed_key` = 'sweet_coffee' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '2 slices', `kcal` = 570, `fiber_g` = 4, `sugar_g` = 8 WHERE `seed_key` = 'pizza' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '2 scoops', `kcal` = 210, `fiber_g` = 1, `sugar_g` = 21 WHERE `seed_key` = 'ice_cream' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 burger', `kcal` = 550, `fiber_g` = 2, `sugar_g` = 9 WHERE `seed_key` = 'burger' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = 'medium portion', `kcal` = 365, `fiber_g` = 4, `sugar_g` = 0 WHERE `seed_key` = 'fries' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 bag (40 g)', `kcal` = 215, `fiber_g` = 2, `sugar_g` = 1 WHERE `seed_key` = 'chips' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '50 g', `kcal` = 270, `fiber_g` = 2, `sugar_g` = 25 WHERE `seed_key` = 'sweets' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '330 ml can', `kcal` = 140, `fiber_g` = 0, `sugar_g` = 35 WHERE `seed_key` = 'soda' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 slice', `kcal` = 350, `fiber_g` = 1, `sugar_g` = 30 WHERE `seed_key` = 'cake' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
UPDATE `categories` SET `portion_label` = '1 drink', `kcal` = 180, `fiber_g` = 0, `sugar_g` = 2 WHERE `seed_key` = 'alcohol' AND `portion_label` IS NULL AND `kcal` IS NULL AND `fiber_g` IS NULL AND `sugar_g` IS NULL;--> statement-breakpoint
INSERT OR IGNORE INTO `daily_goals` (`effective_from`, `kcal_max`, `fiber_min`, `sugar_max`) VALUES ('0000-01-01', 2000, 30, 50);
